import Dance
import DanceFloor as DF


Floor = DF.DanceFloor('Marrie\'s Wedding',3)
print(Floor)
#print('### First 8 Bars ###')
Marrie = Dance.getDance( "Marries Wedding_all")
Dance.showCrips(Marrie, Floor)
Floor = Marrie.DanceMove(Floor)
print(Floor)
'''
#print('### third 4 Bars ###')
Marrie = Dance.getFigure( 'Marries Wedding_Bar 9-12', [1,1])
Dance.showCrips(Marrie, Floor)
Floor = Marrie.DanceMove(Floor)
print(Floor)
#print('### fourth 4 Bars ###')
Marrie = Dance.getFigure( 'Marries Wedding_Bar 13-16', [1,1])
Dance.showCrips(Marrie, Floor)
Floor = Marrie.DanceMove(Floor)
print(Floor)
#print('### fives 4 Bars ###')
Marrie = Dance.getFigure( 'Marries Wedding_Bar 9-12', [1,1])
Dance.showCrips(Marrie, Floor)
Floor = Marrie.DanceMove(Floor)
print(Floor)
#print('### six 4 Bars ###')
Marrie = Dance.getFigure( 'Marries Wedding_Bar 21-24', [1,1])
Dance.showCrips(Marrie, Floor)
Floor = Marrie.DanceMove(Floor)
print(Floor)
Marrie = Dance.getFigure( 'Marries Wedding_Bar 25-32', [1,1])
Dance.showCrips(Marrie, Floor)
Floor = Marrie.DanceMove(Floor)
print(Floor)
Marrie = Dance.getFigure( '6Hrb', [1,1],[])
Dance.showCrips(Marrie, Floor)
Floor = Marrie.DanceMove(Floor)
print(Floor)
'''